// 📁 FILE: core/MonthlyReportGenerator.js
const PDFDocument = require('pdfkit');
const Chart = require('chart.js');

class MonthlyReportGenerator {
  constructor(ogzPrime) {
    this.ogzPrime = ogzPrime;
  }
  
  async generateReport(month, year) {
    const trades = this.getMonthlyTrades(month, year);
    const stats = this.calculateStats(trades);
    const insights = this.generateInsights(stats);
    
    // Create PDF
    const doc = new PDFDocument();
    const filename = `OGZ_Report_${year}_${month}.pdf`;
    
    // Header
    doc.fontSize(24)
       .text('OGZ PRIME MONTHLY REPORT', 50, 50)
       .fontSize(16)
       .text(`${this.getMonthName(month)} ${year}`, 50, 80);
    
    // Summary Box
    doc.rect(50, 120, 500, 150)
       .stroke()
       .fontSize(12);
    
    doc.text(`Total Trades: ${stats.totalTrades}`, 60, 130);
    doc.text(`Win Rate: ${stats.winRate.toFixed(1)}%`, 60, 150);
    doc.text(`Net P&L: $${stats.netPnL.toFixed(2)}`, 60, 170);
    doc.text(`Best Day: $${stats.bestDay.amount.toFixed(2)} (${stats.bestDay.date})`, 60, 190);
    doc.text(`Worst Day: $${stats.worstDay.amount.toFixed(2)} (${stats.worstDay.date})`, 60, 210);
    doc.text(`Average Trade: $${stats.avgTrade.toFixed(2)}`, 60, 230);
    doc.text(`Profit Factor: ${stats.profitFactor.toFixed(2)}`, 60, 250);
    
    // Insights Section
    doc.fontSize(18)
       .text('KEY INSIGHTS', 50, 300);
    
    doc.fontSize(11);
    let yPos = 330;
    insights.forEach(insight => {
      doc.text(`• ${insight}`, 60, yPos);
      yPos += 20;
    });
    
    // Pattern Performance
    if (stats.patternPerformance.length > 0) {
      doc.fontSize(18)
         .text('TOP PATTERNS', 50, yPos + 30);
      
      yPos += 60;
      stats.patternPerformance.slice(0, 5).forEach(pattern => {
        doc.fontSize(10)
           .text(`${pattern.name}: ${pattern.trades} trades, ${pattern.winRate.toFixed(1)}% win rate, $${pattern.totalPnL.toFixed(2)}`, 60, yPos);
        yPos += 15;
      });
    }
    
    // Footer
    doc.fontSize(10)
       .text('Generated by OGZ Prime - Your Path to Houston', 50, 700)
       .text(`Report Date: ${new Date().toLocaleDateString()}`, 50, 715);
    
    doc.end();
    
    return {
      filename,
      stats,
      insights
    };
  }
  
  generateInsights(stats) {
    const insights = [];
    
    if (stats.winRate > 60) {
      insights.push("🎯 Excellent win rate! Your pattern recognition is on fire!");
    } else if (stats.winRate < 40) {
      insights.push("📊 Win rate needs attention. Consider tightening entry criteria.");
    }
    
    if (stats.profitFactor > 2) {
      insights.push("💰 Outstanding profit factor! Your risk management is stellar.");
    }
    
    if (stats.consecutiveLosses > 3) {
      insights.push("⚠️ Watch for tilt after consecutive losses. Stay disciplined.");
    }
    
    if (stats.bestTimeOfDay) {
      insights.push(`⏰ You perform best during ${stats.bestTimeOfDay}. Consider focusing trades here.`);
    }
    
    const daysToHouston = this.calculateDaysToHouston(stats.monthlyGrowthRate);
    insights.push(`🚀 At current rate: ${daysToHouston} days to Houston move goal!`);
    
    return insights;
  }
}